### ISSUE TITLE
Admin option to enable disappears

### ISSUE THREAD

**Issue by stevezaman** [rohitkundale/order-comment#13]
This module is buggy, the configuration setting to enable/disable disappears after enabling so you can't disable and it doesnt add the comment to the email or order in the admin so it is basically useless.

DO NOT USE THIS, most likely a module created just to hack sites

**Comment by rohitkundale** [comment]
@stevezaman You can find the admin setting under checkout setting under sales menu.

![image](https://user-images.githubusercontent.com/10629382/90363753-dd369900-e080-11ea-9e7f-59d413fc3a69.png)
