### ISSUE TITLE
Notice: Undefined index: extension_attributes in PaymentInformationManagement.php

### ISSUE THREAD

**Issue by chloewebfx** [rohitkundale/order-comment#15]
We just upgraded our Magento 2.3 site from PHP 7.1 to 7.4, and now an error flashes very briefly when a user enters a coupon at checkout:
Video: https://webpagefx.mangoapps.com/sf/NDMwMTA1Xzc4NzE1MTE
Still screenshot: https://webpagefx.mangoapps.com/sf/NDMwMTA3Xzc4NzE1MTY

Error in exception.log: [2020-11-18 22:07:39] 
`main.CRITICAL: Report ID: webapi-5fb59b2b651ef; Message: Notice: Undefined index: extension_attributes in /home/doverjew/doverjewelry.webpagefxstage.com/app/code/RohitKundale/OrderComment/Plugin/Model/Checkout/PaymentInformationManagement.php on line 105 {"exception":"[object] (Exception(code: 0): Report ID: webapi-5fb59b2b651ef; Message: Notice: Undefined index: extension_attributes in /home/doverjew/doverjewelry.webpagefxstage.com/app/code/RohitKundale/OrderComment/Plugin/Model/Checkout/PaymentInformationManagement.php on line 105 at /home/doverjew/doverjewelry.webpagefxstage.com/vendor/magento/framework/Webapi/ErrorProcessor.php:208, Exception(code: 0): Notice: Undefined index: extension_attributes in /home/doverjew/doverjewelry.webpagefxstage.com/app/code/RohitKundale/OrderComment/Plugin/Model/Checkout/PaymentInformationManagement.php on line 105 at /home/doverjew/doverjewelry.webpagefxstage.com/vendor/magento/framework/App/ErrorHandler.php:61)"} []`

And there's a 500 error. Request info:
POST to https://oursite.com/rest/default/V1/carts/mine/set-payment-information
Code: 500
Payload: `{cartId: "3", paymentMethod: {method: "free"}}`
Response: `{"message":"Internal Error. Details are available in Magento log file. Report ID: webapi-5fb59c1741355"}`

By changing line 105 in `RohitKundale/OrderComment/Plugin/Model/Checkout/PaymentInformationManagement.php`
from `$comment = $data['paymentMethod']['extension_attributes']['comments'];` to 
`$comment = isset($data['paymentMethod']['extension_attributes']['comments']) ?  $data['paymentMethod']['extension_attributes']['comments'] : false;` we were able to fix there's no longer an error.

It would be great if you could add this quick change to your extension!

**Comment by rohitkundale** [comment]
@chloewebfx Thank you for the heads up. I apply the patch in the module. You can install the latest module https://github.com/rohitkundale/order-comment/releases/tag/2.0.4
