### ISSUE TITLE
Add order comment to email template

### ISSUE THREAD

**Issue by tlygnersjo** [rohitkundale/order-comment#4]
Thanks for a great extension!

Is it possible to use any variable or getting the order comment within email templates (like order confirmation that is being sent to store owner)?

It would be great as store owner if it could be included in email template so that they don't need to sign in to admin to see the order comment. @rohitkundale 

Thanks in advance!

**Comment by tlygnersjo** [comment]
Some help would be really appreciated! @rohitkundale

**Comment by FedeltaMedia** [comment]
I'd like to see this too!

**Comment by rohitkundale** [comment]
@tlygnersjo @Fidelity88 This module doesn't cover this facility but you can easily avail this functionality by creating small modules. You can follow guide from here: https://community.magento.com/t5/Magento-2-x-Technical-Issues/how-to-add-a-comment-on-the-order-confirmation-email/td-p/445291
