### ISSUE TITLE
Breaks Magento_CheckoutAgreements

### ISSUE THREAD

**Issue by twistedindustries** [rohitkundale/order-comment#6]
This module breaks the module Magento_CheckoutAgreements.  I am not exactly sure why but I am guessing that rather than mapping Magento_Checkout/js/action/place-order and Magento_Checkout/js/action/set-payment-information they should be provided as mixins.  Since Magento_CheckoutAgreements uses the code: 

`var config = {
    config: {
        mixins: {
            'Magento_Checkout/js/action/place-order': {
                'Magento_CheckoutAgreements/js/model/place-order-mixin': true
            },
            'Magento_Checkout/js/action/set-payment-information': {
                'Magento_CheckoutAgreements/js/model/set-payment-information-mixin': true
            }
        }
    }
};`

I believe that the mixin isn't being added and I was able to verify that it wasn't via the network tab.  When I disabled this module the mixin showed up as expected.

Note: this happened using Magento 2.2.3

**Comment by rohitkundale** [comment]
@twistedindustries  The module is fixed with Magento_CheckoutAgreements as well as any third-party modules. Please use the latest module for your instance,
